type: object
properties:
  host:
    type: string
  username:
    type: string
  password:
    type: string
  endpointGroups:
    type: array
    items:
      type: string
  metadata:
    type: object
  banned:
    type: boolean
  customProperties:
    type: object
    items:
      type: string
required:
  - "host"
  - "username"
  - "password"
  - "endpointGroups"
  - "metadata"
  - "banned"
  - "customProperties"